classdef CPP_TAC < BaseMed
    properties
        name_conversion = struct( ...
            "A", "pisync_off_times", ...
            "B", "bar_floor_zone_data", ...
            "C", "tac_floor_times_5min_bins", ...
            "D", "bar_floor_times_5min_bins", ...
            "E", "bar_floor_entrances_cumulative_5min_bins", ...
            "F", "tac_floor_entrances_cumulative_5min_bins", ...
            "H", "pisync_on_times", ...
            "I", "pisync_index_counter", ...
            "J", "latency_first_enter_tac", ...
            "K", "latency_first_enter_bar", ...
            "L", "bar_floor_entry_timestamps", ...
            "M", "pisync_on_time_counter", ...
            "N", "bar_floor_exploration_timestamps", ...
            "O", "tac_floor_exploration_timestamps", ...
            "R", "tac_floor_entry_timestamps", ...
            "T", "session_time", ...
            "W", "tac_floor_zone_data" ...
            );

        time_arrays = [];
    end

    methods
        function set_sync_arrays(obj, gpio_path)
            error("Needs implemented")
        end
    end
end