classdef DD < BaseMed
    properties
    name_conversion = struct( ...
        "A", "initial_lever_response", ...
        "B", "delay_resp_choice", ...
        "C", "delay_resp_force", ...
        "D", "session_delay_and_consec_resp", ...
        "E", "initial_lever_latency", ...
        "F", "choice_lever_latency", ...
        "G", "force_lever_latency", ...
        "H", "trial_type", ...
        "I", "inter_trial_interval", ...
        "J", "imm_resp_choice", ...
        "K", "trial_counter", ...
        "L", "imm_resp_force", ...
        "M", "missed_choice", ...
        "N", "time_end_of_trial", ...
        "O", "imm_lever_reinforcer_value", ...
        "P", "pellet_loop_and_adjustment", ...
        "Q", "session_condition", ...
        "R", "reinforcer_counts", ...
        "S", "array_elements_U_V_W_X_Y_Z", ...
        "T", "timer_and_latencies", ...
        "U", "delay_resp_initial", ...
        "V", "delay_resp_choice", ...
        "W", "delay_resp_forced_delay", ...
        "X", "imm_resp_initial", ...
        "Y", "imm_resp_choice", ...
        "Z", "imm_resp_forced_imm" ...
    );

    time_arrays = [
        "time_end_of_trial", ...
        "delay_resp_initial", ...
        "delay_resp_forced_delay", ...
        "imm_resp_initial", ...
        "imm_resp_choice", ...
        "imm_resp_forced_imm"]
    end

    methods
        function set_sync_arrays(obj, gpio_path)
            gpio = obj.get_pi_gpio(gpio_path);


            pi_on = gpio.posix(gpio.Pin==16 & gpio.Event==1);
            med_end = obj.time_end_of_trial;

            obj.sync_med = med_end(1:end-1);
            obj.sync_posix = pi_on(2:end) - 0.01;
        end
    end
end