classdef RAP < BaseMed
    properties
        name_conversion = struct( ...
            "A", "num_left_licks", ...
            "B", "num_right_licks", ...
            "C", "left_sipper_tripped_flag", ...
            "D", "right_sipper_tripped_flag", ...
            "E", "left_lick_times_sec", ...
            "F", "right_lick_times_sec", ...
            "G", "total_licks", ...
            "H", "pisync_on_times", ...
            "I", "pisync_signal_counter", ...
            "J", "beam_state_transition_counts", ...
            "K", "pisync_on_time_ms", ...
            "L", "pisync_off_times", ...
            "P", "beam1_break_times", ...
            "Q", "beam2_break_times", ...
            "R", "beam3_break_times", ...
            "S", "beam4_break_times", ...
            "U", "beam5_break_times", ...
            "V", "beam6_break_times", ...
            "T", "time_seconds" ...
            );

        time_arrays = [
            "pisync_on_time_ms", ...
            ]
    end

    methods
        function set_sync_arrays(obj, gpio_path)
            gpio = obj.get_pi_gpio(gpio_path);
            obj.sync_med = obj.pisync_on_times;
            obj.sync_posix = gpio.posix(gpio.Pin==16 & gpio.Event==1);
        end
    end
end