classdef TAC < BaseMed
    properties
        name_conversion = struct( ...
            "A", "pisync_on_times_choice", ...
            "B", "counters", ...
            "C", "iti_times", ...
            "D", "iti_selected_each_trial", ...
            "E", "num_forced_vs_choice", ...
            "F", "forced_trial_selection_list", ...
            "G", "forced_trial_type", ...
            "H", "pisync_on_times_forced", ...
            "I", "pisync_index_counter", ...
            "J", "num_choice_vs_forced", ...
            "K", "tac_lick_timestamps", ...
            "L", "bar_lick_timestamps", ...
            "M", "trial_types_session_order", ...
            "N", "engaged_trial_counter", ...
            "O", "tac_entry_beam_break_timestamps", ...
            "P", "bar_entry_beam_break_timestamps", ...
            "Q", "tac_sipper_beam_break_timestamps", ...
            "R", "bar_sipper_beam_break_timestamps", ...
            "T", "session_time" ...
            );

        time_arrays = [];
    end

    methods
        function set_sync_arrays(obj, gpio_path)
            error("Needs implemented")
        end
    end
end