classdef TwoCAP < BaseMed
    properties
        name_conversion = struct( ...
            "T", "time_seconds", ...
            "A", "num_completed_trials", ...
            "D", "allowed_trial_types", ...
            "X", "trial_type_number", ...
            "M", "output_event", ...
            "N", "output_event_time_sec", ...
            "L", "output_event_counter", ...
            "Z", "intertrial_interval_sec", ...
            "I", "allowed_iti_times_sec", ...
            "J", "beam_state_transition_counts", ...
            "P", "beam1_break_times", ...
            "Q", "beam2_break_times", ...
            "R", "beam3_break_times", ...
            "S", "beam4_break_times", ...
            "U", "beam5_break_times", ...
            "V", "beam6_break_times", ...
            "E", "left_lick_times_sec", ...
            "F", "right_lick_times_sec", ...
            "G", "left_right_lick_counts", ...
            "C", "cs_minus_likelihood", ...
            "K", "cs_minus_status", ...
            "W", "cs_minus_hold_status", ...
            "O", "cs_minus_opportunity_count" ...
            );

        time_arrays = [];
    end

    methods
        function set_sync_arrays(obj, gpio_path)
            error("Needs implemented")
        end
    end
end